//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienDanThaoLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public string MaBL { get; set; }
        public string IDCha { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string TrangThai { get; set; }
        public string MaBV { get; set; }
        public string MaTV { get; set; }
        public string MaQTV { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual QuanTriVien QuanTriVien { get; set; }
    }
}
